import { getChangelogUrl } from './changelog';
import { assessRisk } from './risk-assessor';
import type { PackageGroup, UpdateType } from './types';

const UPDATE_TYPE_BADGE: Record<UpdateType, string> = {
  patch: '🔵 PATCH',
  minor: '🟡 MINOR',
  major: '🔴 MAJOR',
};

export function composePrTitle(group: PackageGroup): string {
  const { packages, highestUpdateType, name } = group;

  if (packages.length === 1) {
    const pkg = packages[0];
    return `chore(deps): update \`${pkg.packageName}\` ${pkg.currentVersion} → ${pkg.latestVersion} (${pkg.updateType})`;
  }

  // For groups, show the version only when all packages converge on the same target
  const uniqueTargets = [...new Set(packages.map((p) => p.latestVersion))];
  const versionSuffix =
    uniqueTargets.length === 1 ? ` → ${uniqueTargets[0]}` : '';
  return `chore(deps): update ${name} packages${versionSuffix} (${highestUpdateType})`;
}

export async function composePrBody(group: PackageGroup): Promise<string> {
  const { packages, highestUpdateType } = group;
  const risk = assessRisk(highestUpdateType);

  // Fetch changelog URLs in parallel
  const changelogUrls = await Promise.all(
    packages.map(async (pkg) => ({
      packageName: pkg.packageName,
      url: await getChangelogUrl(pkg.packageName),
    })),
  );
  const changelogMap = new Map(
    changelogUrls.map(({ packageName, url }) => [packageName, url]),
  );

  const tableRows = packages.map((pkg) => {
    const url = changelogMap.get(pkg.packageName);
    const toCell = url
      ? `[\`${pkg.latestVersion}\`](${url}/tag/v${pkg.latestVersion})`
      : `\`${pkg.latestVersion}\``;
    return `| \`${pkg.packageName}\` | \`${pkg.currentVersion}\` | ${toCell} | ${UPDATE_TYPE_BADGE[pkg.updateType]} |`;
  });

  const affectedFiles = [
    ...new Set(
      packages.flatMap((pkg) => pkg.occurrences.map((o) => o.packageJsonPath)),
    ),
  ];

  const releaseLinks = changelogUrls
    .filter(({ url }) => url !== null)
    .map(({ packageName, url }) => `- [\`${packageName}\` releases](${url})`);

  const lines: string[] = [
    `## Breaking Change Risk: ${risk.level}`,
    '',
    `> [!${risk.callout}]`,
    `> ${risk.description}`,
    '',
    '## Packages',
    '',
    '| Package | From | To | Type |',
    '|---------|------|----|------|',
    ...tableRows,
    '',
  ];

  if (affectedFiles.length > 0) {
    lines.push('## Files Updated', '');
    for (const f of affectedFiles) {
      lines.push(`- \`${f}\``);
    }
    lines.push('');
  }

  if (releaseLinks.length > 0) {
    lines.push('## Release Notes', '', ...releaseLinks, '');
  }

  lines.push(
    '---',
    '*Auto-generated by [PatchPulse](https://github.com/barrymichaeldoyle/patch-pulse)*',
  );

  return lines.join('\n');
}
